name: Build on Release

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Set API key in environment
      run: |
        echo "Creating API key variable in GITHUB_ENV"
        echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

    - name: Set PowerShell Execution Policy to Bypass
      run: |
        Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file (using API_KEY)
      run: |
        echo "Creating X_API token from GITHUB_ENV"
        echo "X_API=$GITHUB_ENV:API_KEY" > .env
        echo ".env file created with API_KEY"

    - name: Build On Windows
      run: |
        echo "Building on Windows"
        
        # Set up Chocolatey
        echo "Setting up Chocolatey"
        Set-ExecutionPolicy AllSigned
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

        # Install Inno Setup Command Line Compiler
        echo "Installing Inno Setup"
        choco install innosetup

        # Build .exe
        echo "Building .exe with pyinstaller"
        pyinstaller build_instructions/EasyPunchCard.spec

        # Build Installer
        echo "Building installer with iscc"
        iscc build_instructions/easypunchcard_setup_script.iss

        # Delete all artifacts except the setup exe
        echo "Deleting artifacts except for installer"
        powershell -Command "Get-ChildItem 'dist' -File | Where{$_.Name -NotMatch 'EasyPunchCard_setup.exe'} | Remove-Item"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-${{ runner.os }}-${{ github.run_id }}
        path: dist/

    - name: Upload Windows Release Asset
      if: runner.os == 'Windows'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: softprops/action-gh-release@v2.3.3
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/EasyPunchCard_setup.exe
        asset_name: EasyPunchCard.exe
        asset_content_type: application/octet-stream
